-- megafunction wizard: %NCO v10.0%
-- GENERATION: XML

-- ============================================================
-- Megafunction Name(s):
-- 			NCO_lab3_st
-- ============================================================
-- Generated by NCO 10.0 [Altera, IP Toolbench 1.3.0 Build 218]
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
-- ************************************************************
-- Copyright (C) 1991-2012 Altera Corporation
-- Any megafunction design, and related net list (encrypted or decrypted),
-- support information, device programming or simulation file, and any other
-- associated documentation or information provided by Altera or a partner
-- under Altera's Megafunction Partnership Program may be used only to
-- program PLD devices (but not masked PLD devices) from Altera.  Any other
-- use of such megafunction design, net list, support information, device
-- programming or simulation file, or any other related documentation or
-- information is prohibited for any other purpose, including, but not
-- limited to modification, reverse engineering, de-compiling, or use with
-- any other silicon devices, unless such use is explicitly licensed under
-- a separate agreement with Altera or a megafunction partner.  Title to
-- the intellectual property, including patents, copyrights, trademarks,
-- trade secrets, or maskworks, embodied in any such megafunction design,
-- net list, support information, device programming or simulation file, or
-- any other related documentation or information provided by Altera or a
-- megafunction partner, remains with Altera, the megafunction partner, or
-- their respective licensors.  No other licenses, including any licenses
-- needed under any third party's intellectual property, are provided herein.

library IEEE;
use IEEE.std_logic_1164.all;

ENTITY NCO_lab3 IS
	PORT (
		phi_inc_i	: IN STD_LOGIC_VECTOR (27 DOWNTO 0);
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		clken	: IN STD_LOGIC;
		freq_mod_i	: IN STD_LOGIC_VECTOR (27 DOWNTO 0);
		fsin_o	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		out_valid	: OUT STD_LOGIC
	);
END NCO_lab3;

ARCHITECTURE SYN OF NCO_lab3 IS


	COMPONENT NCO_lab3_st
	PORT (
		phi_inc_i	: IN STD_LOGIC_VECTOR (27 DOWNTO 0);
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		clken	: IN STD_LOGIC;
		freq_mod_i	: IN STD_LOGIC_VECTOR (27 DOWNTO 0);
		fsin_o	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		out_valid	: OUT STD_LOGIC
	);

	END COMPONENT;

BEGIN

	NCO_lab3_st_inst : NCO_lab3_st
	PORT MAP (
		phi_inc_i  =>  phi_inc_i,
		fsin_o  =>  fsin_o,
		clk  =>  clk,
		reset_n  =>  reset_n,
		clken  =>  clken,
		out_valid  =>  out_valid,
		freq_mod_i  =>  freq_mod_i
	);


END SYN;


-- =========================================================
-- NCO Wizard Data
-- ===============================
-- DO NOT EDIT FOLLOWING DATA
-- @Altera, IP Toolbench@
-- Warning: If you modify this section, NCO Wizard may not be able to reproduce your chosen configuration.
-- 
-- Retrieval info: <?xml version="1.0"?>
-- Retrieval info: <MEGACORE title="NCO"  version="10.0"  build="218"  iptb_version="1.3.0 Build 218"  format_version="120" >
-- Retrieval info:  <NETLIST_SECTION active_core="NCO_lab3_st" >
-- Retrieval info:   <STATIC_SECTION>
-- Retrieval info:    <PRIVATES>
-- Retrieval info:     <NAMESPACE name = "parameterization">
-- Retrieval info:      <PRIVATE name = "use_mem" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_type" value="M512"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RAW" value="16"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MAX" value="256"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfs1" value="xxx.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "devicefamily" value="Cyclone IV E"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DPRI" value="5"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DEVICE" value="CycloneIVE"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ACCUM_SCLR" value="0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ARCH" value="TRIG_ARCH"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "TARGET" value="CycloneIVE"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "WANT_DITHER" value="YES"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "APRP" value="16"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "CK_VALUE" value="10"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "CK_UNIT" value="ns"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "CK_MULT" value="e-9"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FSAMP_VALUE" value="50"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FREQ_VALUE" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MPR" value="16"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "APR" value="28"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "APRI" value="16"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FSAMP_UNIT" value="MHz"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FSAMP_MULT" value="1e6"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FREQ_UNIT" value="MHz"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FREQ_MULT" value="1e6"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "WANT_PMOD" value="NO"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "WANT_FMOD" value="YES"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DUAL_NOT_SGL_OP" value="WANT_SIN_ONLY"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FMOD_PIPELINE" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "PMOD_PIPELINE" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "APRF" value="28"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MULT_TYPE" value="DEDICATED"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "CORDIC_TYPE" value="PARALLEL"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "CORDIC_PIPE" value="2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "THROUGHPUT" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUMCH" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "WANT_VLOG_SIM" value="YES"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "WANT_VHDL_SIM" value="YES"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "WANT_MATLAB" value="YES"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "WANT_VEC" value="YES"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "PHI_INC" value="5368709"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MODULE_NAME" value="NCO_lab3_st"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NETLIST_FILE_NAME" value="NCO_lab3_st.v"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "PHASE_INC" value="4096"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FREQ_INC" value="16777216"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RCFC" value="NCO_lab3_cos_c.mif"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RCVC" value="NCO_lab3_cos_c.v"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RCHC" value="NCO_lab3_cos_c.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RCFF" value="NCO_lab3_cos_f.mif"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RCVF" value="NCO_lab3_cos_f.v"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RCHF" value="NCO_lab3_cos_f.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RSFC" value="NCO_lab3_sin_c.mif"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RSVC" value="NCO_lab3_sin_c.v"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RSHC" value="NCO_lab3_sin_c.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RSFF" value="NCO_lab3_sin_f.mif"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RSVF" value="NCO_lab3_sin_f.v"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RSHF" value="NCO_lab3_sin_f.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MAXC" value="4096"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MAXF" value="4096"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RAWC" value="8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RAWF" value="8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RNWC" value="256"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RNWF" value="256"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "RDW" value="16"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_LCELLS" value="1123"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_MEM_BITS" value="12288"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_EABS" value="2"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_DSP_BLOCKS" value="4"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen_enable">
-- Retrieval info:      <PRIVATE name = "language" value="VHDL"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enabled" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "gb_enabled" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen">
-- Retrieval info:      <PRIVATE name = "filename" value="NCO_lab3.vho"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "greybox">
-- Retrieval info:      <PRIVATE name = "filename" value="NCO_lab3_syn.v"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "quartus_settings">
-- Retrieval info:      <PRIVATE name = "DEVICE" value="EP4CE115F29C7"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FAMILY" value="Cyclone IV E"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "serializer"/>
-- Retrieval info:    </PRIVATES>
-- Retrieval info:    <FILES/>
-- Retrieval info:    <PORTS>
-- Retrieval info:     <PORT name = "phi_inc_i" direction="INPUT"  connect_to="phi_inc_i"  default="NODEFVAL"  high_width="27"  low_width="0"  description="" />
-- Retrieval info:     <PORT name = "fsin_o" direction="OUTPUT"  connect_to="fsin_o"  default="NODEFVAL"  high_width="15"  low_width="0"  description="" />
-- Retrieval info:     <PORT name = "clk" direction="INPUT"  connect_to="clk"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "reset_n" direction="INPUT"  connect_to="reset_n"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "clken" direction="INPUT"  connect_to="clken"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "out_valid" direction="OUTPUT"  connect_to="out_valid"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "freq_mod_i" direction="INPUT"  connect_to="freq_mod_i"  default="NODEFVAL"  high_width="27"  low_width="0"  description="" />
-- Retrieval info:    </PORTS>
-- Retrieval info:    <LIBRARIES/>
-- Retrieval info:   </STATIC_SECTION>
-- Retrieval info:  </NETLIST_SECTION>
-- Retrieval info: </MEGACORE>
-- =========================================================
-- RELATED_FILES: NCO_lab3_st.v, NCO_lab3.vhd;
-- IPFS_FILES: NCO_lab3.vho;
-- =========================================================
